# Generated by Django 3.0.3 on 2020-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_posts', models.CharField(max_length=10)),
                ('followed_users', models.CharField(max_length=20)),
            ],
        ),
    ]
