# Generated by Django 3.0.3 on 2020-02-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_posts',
        ),
    ]
