# Generated by Django 3.0.3 on 2020-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0003_remove_user_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
