# Generated by Django 3.0.3 on 2020-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0004_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_ids',
            field=models.CharField(default='', max_length=20),
        ),
    ]
