# Generated by Django 3.0.3 on 2020-03-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0005_user_post_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_ids',
        ),
    ]
