# Generated by Django 3.0.3 on 2020-03-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0007_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secretChar',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_caption',
            field=models.TextField(max_length=144),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
