# Generated by Django 3.0.3 on 2020-03-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0009_auto_20200326_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user_name',
        ),
    ]
