# Generated by Django 3.0.3 on 2020-03-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0010_auto_20200326_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='username',
        ),
    ]
