# Generated by Django 3.0.3 on 2020-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterapp', '0011_auto_20200326_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=',', max_length=200),
        ),
    ]
